services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: Loatodo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - /Users/minhyeok/Desktop/LostarkTodo/data/mysql:/var/lib/mysql
