### 1. 회원가입전 이메일 인증번호 전송
POST http://localhost:5000/v3/mail
Content-Type: application/json

{
  "mail": "repeater2487@naver.com"
}

### 2. 회원가입전 이메일 인증번호 인증
POST http://localhost:5000/v3/mail/auth
Content-Type: application/json

{
  "mail": "repeater2487@naver.com",
  "number": 113376
}

### 3. 1차 회원가입
POST http://localhost:5000/v3/auth/signup
Content-Type: application/json

{
  "mail": "repeater2487@naver.com",
  "number": 113376,
  "password": "123456",
  "equalPassword": "123456"
}

### 4. 1차 회원가입 후 캐릭터 추가
POST http://localhost:5000/v3/auth/character
Content-Type: application/json

{
  "username": "repeater2487@naver.com",
  "apiKey": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyIsImtpZCI6IktYMk40TkRDSTJ5NTA5NWpjTWk5TllqY2lyZyJ9.eyJpc3MiOiJodHRwczovL2x1ZHkuZ2FtZS5vbnN0b3ZlLmNvbSIsImF1ZCI6Imh0dHBzOi8vbHVkeS5nYW1lLm9uc3RvdmUuY29tL3Jlc291cmNlcyIsImNsaWVudF9pZCI6IjEwMDAwMDAwMDAzODcyNDcifQ.cQUYdct2tuSUMYowf-QB90B0KZ7mBz1czsqT-nNrX4GGPA0409iEK9b1JVqCVpqRP05xrKHEKogcrFP0fBg9M_YgyIBQBZKqFSmPtQICzyEdpzynyeDntz1szE7RpLVik3lM6D6DLClnxA_a_yV8OEuI4YNz4OGhxLxKzwxSd6g17j8H4DAeoXuA5FcdEDwXZUweOGnE4hVOD9pN3FTsY2_rWDJAP9wRx4Uy3cPsoB5_Rqcxj4cJH1PWwgyB_fdhfvuRF9z1dnRZ4vt4ZHk2S6gjwgsAZ7vmLi9evBU0D6HJ9G2-g67lkNCVbPFriC385GkxCPOKOHU3UdPv3UppVQ",
  "characterName": "이다"
}
